# Railway.app deployment configuration
# Docs: https://docs.railway.app

# This file tells Railway how to deploy your services

version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: ${{PORT}}
      DATABASE_URL: ${{DATABASE_URL}}
      ADMIN_API_KEY: ${{ADMIN_API_KEY}}
      STALE_MINUTES: ${{STALE_MINUTES}}
      HOST: "0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${{RAILWAY_BACKEND_URL}}
      PORT: ${{PORT}}
      HOSTNAME: "0.0.0.0"
    depends_on:
      - backend
